### ISSUE TITLE
Coin development

### ISSUE THREAD

**Issue by dimitrkovalsky** [cbrnrd/Cozy#1]
Hello,

I found our coin on github and I am interested in it development. Could you describe something about algorithms and features of your coin? I can contribute to you repository if project will be interesting.

My mail: dimitrkovalsky@gmail.com

Regards,
Dmytro

**Comment by cbrnrd** [comment]
Hi, thank you for your interest! The coin has support for both PoW and PoS and uses SHA-256 as its hashing algorithm. Let me know if you need any more info!

**Comment by dimitrkovalsky** [comment]
How can I run mining process? Do you have some plan  for further development (some exchange listing)?

**Comment by cbrnrd** [comment]
I did not implement a miner (just due to java being particularly slow at that much computing vs something like crystal or C). I have plans to get this listed on bittrex and/or kraken in the near future. If you wanted to contribute, a miner in crystal/c/c++ would be a great place to start (I would also love to help you out with that if you choose to make it)

**Comment by dimitrkovalsky** [comment]
Actually it does not matter how fast miner. Because it is new coin. And I think for start miner can be written on pure java and I can do it. Can you give some explanation where to start and do you have some mining puzzle? And one more, how can I get some coin amount?

**Comment by cbrnrd** [comment]
Some places in code are [here](https://github.com/cbrnrd/Cozy/blob/810215b007fb0154446e0d7a9a9cea40d64ccf03/src/main/java/io/codepace/cozy/Certificate.java#L109) and [here](https://github.com/cbrnrd/Cozy/blob/810215b007fb0154446e0d7a9a9cea40d64ccf03/src/main/java/io/codepace/cozy/Certificate.java#L135) . These methods have to do with checking certificate nonces, but the algorithm is the same.

**Comment by cbrnrd** [comment]
Right now, there is no node running full time, so there is technically no coins in circulation. I plan to get a full node up and running 24/7 within the next week or so.

**Comment by dimitrkovalsky** [comment]
ok, I will try to investigate code more deep
