### ISSUE TITLE
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by Mignet** [cbrnrd/Cozy#2]
hi,there.
how to start the first node or the first block?

**Comment by cbrnrd** [comment]
Hi! Can you please post the full log output so I know where the problem is happening? Thanks :)

**Comment by cbrnrd** [comment]
I think I figured it out. The error happens because the testnet is not launched yet. in `Constants.java` the reliable peer is set to `127.0.0.1:8015`. When I launch a reliable peer, this will be updated and the bug should™ be fixed.

**Comment by Mignet** [comment]
Thx for your reply
